In [1]:
#amazing things will follow

import numpy as np

In [5]:
np.random.seed(7)
november_sales = np.random.randint(25,200, size=(4,7))
print('Sales for November month:\n',november_sales)

Sales for November month:
 [[ 50  92 176 128 117 167  48]
 [ 97 114 135  67 161 192  93]
 [152 160 197  25 100  80  31]
 [ 44  69  94  81 177 137  59]]


In [6]:
#this gave sales for 7 days a week, 4 times; a month


In [7]:
#mean sales; for coffees sold per day in November month
print('Mean:', november_sales.mean())

Mean: 108.67857142857143


In [8]:
#mean sales for Mondays only
print('Mean for Monday:', november_sales[:,1].mean())

Mean for Monday: 108.75


In [10]:
#day with max sale in the entire month
print('Maximum sale of:', november_sales.max())

Maximum sale of: 197


In [14]:
#now we want to find which day of the month was this in
print('Day of maximum sale was January', (november_sales.argmax()+1))

Day of maximum sale was January 17
