In [1]:
import numpy as np

In [2]:
#numpy practice

lists= [[1,2,3], [4,5,6], [7,8,9]]

array1 = np.array(lists)
print(array1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
print(array1.shape, array1.dtype)

(3, 3) int32


In [10]:
a = np.linspace(1,10,10)

In [11]:
print(a)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [12]:
b = np.arange(1,10,1)
print(b)

[1 2 3 4 5 6 7 8 9]


In [13]:
c = np.logspace(1,10,10)
print(c)

[1.e+01 1.e+02 1.e+03 1.e+04 1.e+05 1.e+06 1.e+07 1.e+08 1.e+09 1.e+10]


In [15]:
d = np.zeros(9)
print(d)

[0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [16]:
e = np.diag([1,2,3,4])
print(e)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [18]:
f = np.eye(3)
print(f)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [19]:
#summing numbers in an array
for i in b:
    x = sum(i)
    
print(x)

TypeError: 'numpy.int32' object is not iterable

In [20]:
#therefore we use an inbuilt function
print(b.sum())

45


In [21]:
#printing rowwise and columnwise sums of elements in an array
print('Sum of rows:', array1.sum(axis=1))

Sum of rows: [ 6 15 24]


In [22]:
print('Sum of columns:', array1.sum(axis=0))

Sum of columns: [12 15 18]


In [23]:
print(array1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [25]:
x = np.arange(1,6,1)
print(x)

[1 2 3 4 5]


In [26]:
y = x+1
print(y)


[2 3 4 5 6]


In [27]:
print('X:',x)
print('Y:',y)

X: [1 2 3 4 5]
Y: [2 3 4 5 6]


In [28]:
#concatenating both arrays
np.hstack((x,y))

array([1, 2, 3, 4, 5, 2, 3, 4, 5, 6])

In [29]:
np.vstack((x,y))

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6]])

In [30]:
np.dstack((x,y))

array([[[1, 2],
        [2, 3],
        [3, 4],
        [4, 5],
        [5, 6]]])